export const MOCK_COURSES = [
  { id: '1', name: '유어파크골프장', city_province: '경남', address: '경상남도 창녕군 유어면 미구리 588', hole_count: 18 },
  { id: '2', name: '연산파크골프장', city_province: '충남', address: '충청남도 논산시 연산면 표정리 249-2', hole_count: 18 },
  { id: '3', name: '술뫼파크골프장', city_province: '경남', address: '경상남도 김해시 한림면 시산리 495-2', hole_count: 18 },
  { id: '4', name: '도개파크골프장', city_province: '경북', address: '경상북도 구미시 도개면 궁기리 829-1', hole_count: 18 },
  { id: '5', name: '남구 대공원 파크골프장', city_province: '울산', address: '울산광역시 남구 대공원로 94', hole_count: 18 },
  { id: '6', name: '비산파크골프장C-D', city_province: '대구', address: '대구광역시 서구 비산동 2920', hole_count: 18 },
  { id: '7', name: '심학산파크골프장', city_province: '경기', address: '경기도 파주시 양지안길 1 (동패동)', hole_count: 18 },
  { id: '8', name: '북구 검단파크골프장', city_province: '대구', address: '대구광역시 북구 검단동 276', hole_count: 18 },
  { id: '9', name: '삼량진파크골프장', city_province: '경남', address: '경상남도 밀양시 삼량진읍 송지리 456-6', hole_count: 18 },
  { id: '10', name: '남구 태화강 파크골프장', city_province: '울산', address: '울산광역시 남구 신정동 391', hole_count: 18 },
  { id: '11', name: '염주파크골프장', city_province: '광주', address: '광주광역시 서구 금화로 278', hole_count: 18 },
  { id: '12', name: '동탄2수질복원센터파크골프장', city_province: '경기', address: '경기도 화성시 방교동 795', hole_count: 18 },
  { id: '13', name: '선학파크골프장', city_province: '인천', address: '인천 연수구 경원대로 526', hole_count: 18 },
  { id: '14', name: '장암파크골프장', city_province: '경기', address: '경기 의정부시 장암동 299-11 (중랑천 호장교 인근)', hole_count: 18 },
  { id: '15', name: '동부양산 파크골프장', city_province: '경남', address: '경남남도 양산시 덕명로 76', hole_count: 18 },
  { id: '16', name: '화명파크골프장', city_province: '부산', address: '부산광역시 북구 화명동 1718-14 화명생태공원', hole_count: 18 },
  { id: '17', name: '평창 파크골프장', city_province: '강원', address: '강원특별자치도 평창군 평창읍 제방길 101', hole_count: 18 },
  { id: '18', name: '해평파크골프장', city_province: '경북', address: '경상북도 구미시 해평면 낙산리1095-34', hole_count: 18 },
  { id: '19', name: '장호원파크골프장', city_province: '경기', address: '경기도 이천시 장호원읍 오남리 304-5(청미천 둔치)', hole_count: 18 },
  { id: '20', name: '서천군노인복지관파크골프장', city_province: '충남', address: '청남도 서천군 종천면 충서로302번길 88-26', hole_count: 18 },
  { id: '21', name: '대평파크골프장', city_province: '세종', address: '세종특별자치시 대평동 578-12', hole_count: 18 },
  { id: '22', name: '시천(덕산)파크골프장', city_province: '경남', address: '경상남도 산청군 시천면 사리 900-48', hole_count: 18 },
  { id: '23', name: '경산파크골프장', city_province: '경북', address: '경상북도 경산시 강변동로 369', hole_count: 18 },
  { id: '24', name: '원덕파크골프장', city_province: '강원', address: '강원특별자치도 삼척시 원덕읍 월천리 587번지', hole_count: 18 },
  { id: '25', name: '백마강생활체육공원 파크골프장', city_province: '충남', address: '충청남도 부여군 부여읍 구교리 282-1', hole_count: 18 },
  { id: '26', name: '서충주파크골프장', city_province: '충북', address: '충주시 대소원면 영평리 479-43번', hole_count: 18 },
  { id: '27', name: '정촌파크골프장', city_province: '경남', address: '경상남도 진주시 정촌면 예하리 1297-15', hole_count: 18 },
  { id: '28', name: '광주 효령파크골프장', city_province: '광주', address: '광주광역시 북구 하서로 950', hole_count: 18 },
  { id: '29', name: '비비정파크골프장', city_province: '전북', address: '전북특별자치도 완주군 삼례읍 후정리142-1 비비정공원 내', hole_count: 18 },
  { id: '30', name: '삼랑진파크골프장', city_province: '경남', address: '경상남도 밀양시 삼랑진읍 송지리 456-6번지', hole_count: 18 },
  { id: '31', name: '다락원파크골프장', city_province: '서울', address: '서울 도봉구 도봉동 1-28', hole_count: 18 },
  { id: '32', name: '백세파크골프장', city_province: '충남', address: '충청남도 청양군 청양읍 은천동길 16-6 백세공원 내', hole_count: 18 },
  { id: '33', name: '서면파크골프장', city_province: '전남', address: '전라남도 순천시 서면 강청리 828', hole_count: 18 },
  { id: '34', name: '봉화파크골프장', city_province: '경북', address: '경상북도 봉화군 봉화읍 내성리 내성천 둔치', hole_count: 18 },
  { id: '35', name: '남악파크골프장', city_province: '전남', address: '전라남도 무안군 삼향읍 남악리 2597', hole_count: 18 },
  { id: '36', name: '곡강파크골프장', city_province: '경북', address: '경상북도 포항시 북구 흥해읍 용전리 965', hole_count: 18 },
  { id: '37', name: '하빈파크골프장_폐장', city_province: '대구', address: '대구광역시 달성군 하빈면 봉촌리 797', hole_count: 18 },
  { id: '38', name: '화천 산천어파크골프장(1구장)', city_province: '강원', address: '강원특별자치도 화천군 하남면 춘화로 3061-17', hole_count: 18 },
  { id: '39', name: '철원군파크골프장', city_province: '강원', address: '강원도 철원군 갈말읍 군탄리 1084', hole_count: 18 },
  { id: '40', name: '철우파크골프장', city_province: '경북', address: '경상북도 안동시 운흥동 구 안동역내', hole_count: 18 },
  { id: '41', name: '함안파크골프장', city_province: '경남', address: '경상남도 함안군 법수면 법정로 200-39', hole_count: 18 },
  { id: '42', name: '청주 미호강 파크골프장', city_province: '충북', address: '충청북도 청주시 흥덕구 미호로 99', hole_count: 18 },
  { id: '43', name: '신호파크골프장', city_province: '부산', address: '부산광역시 강서구 신호동 315-1', hole_count: 18 },
  { id: '44', name: '부여파크골프장', city_province: '충남', address: '충청남도 부여군 부여읍 군수리 268-3', hole_count: 18 },
  { id: '45', name: '삼호파크골프장', city_province: '전남', address: '전라남도 영암군 삼호읍 종합공원길 11', hole_count: 18 },
  { id: '46', name: '장성군 A파크골프장', city_province: '전남', address: '전라남도 장성군 황룡면 월평리 590-1', hole_count: 18 },
  { id: '47', name: '성저파크골프장', city_province: '경기', address: '경기도 고양시 일산서구 중앙로 1601일원', hole_count: 18 },
  { id: '48', name: '고령대가야파크골프장', city_province: '경북', address: '경상북도 고령군 대가야읍 장기리 320-1', hole_count: 18 },
  { id: '49', name: '평택파크골프장', city_province: '경기', address: '경기도 평택시 비전동 1005-1', hole_count: 18 },
  { id: '50', name: '하남시파크골프장', city_province: '경기', address: '경기도 하남시 미사대로505 미사경정공원 내', hole_count: 18 },
  { id: '51', name: '고아파크골프장', city_province: '경북', address: '경상북도 구미시 고아읍 예강리 695-1', hole_count: 18 },
  { id: '52', name: '대원레포츠공원 파크골프장', city_province: '경남', address: '경상남도 창원시 의창구 두대로 46 (대상공원내)', hole_count: 18 },
  { id: '53', name: '금소파크골프장', city_province: '경북', address: '경상북도 안동시 임하면 금소리 627번지', hole_count: 18 },
  { id: '54', name: '조만강 장애인 파크골프장', city_province: '경남', address: '경상남도 김해시 장유면 칠산로 127-25', hole_count: 18 },
  { id: '55', name: '미사리파크골프장', city_province: '경기', address: '경기도 하남시 미사동 608 (하남나무고아원)', hole_count: 18 },
  { id: '56', name: '와룡지구 파크골프장', city_province: '경남', address: '경상남도 진주시 금산면 장사리 1769', hole_count: 18 },
  { id: '57', name: '비안파크골프장', city_province: '경북', address: '경북 의성군 비안면 동부리 159-2', hole_count: 18 },
  { id: '58', name: '함안샛담파크골프장', city_province: '경남', address: '경상남도 함안군 함안면 샛담길 35-15', hole_count: 18 },
  { id: '59', name: '유가한정파크골프장', city_province: '대구', address: '대구광역시 달성군 유가읍 한정리 596-1 (차천변)', hole_count: 18 },
  { id: '60', name: '수성파크골프장', city_province: '대구', address: '대구광역시 수성구 고모동 6-2', hole_count: 18 },
  { id: '61', name: '무안파크골프장', city_province: '경남', address: '경상남도 밀양시 무안면 신법리 262-2', hole_count: 18 },
  { id: '62', name: '혁신도시파크골프장', city_province: '전남', address: '전라남도 나주시 빛가람동 4-346', hole_count: 18 },
  { id: '63', name: '벽진면파크골프장', city_province: '경북', address: '경상북도 성주군 벽진면 체육공원', hole_count: 18 },
  { id: '64', name: '구미 양포파크골프장', city_province: '경북', address: '경상북도 구미시 양호동 608-6', hole_count: 18 },
  { id: '65', name: '정촌죽봉파크골프장', city_province: '경남', address: '경상남도 진주시 정촌면 화개리 553-8', hole_count: 18 },
  { id: '66', name: '유등천파크골프장', city_province: '대전', address: '대전광역시 서구 만년동 516 일원', hole_count: 18 },
  { id: '67', name: '송월동파크골프장', city_province: '전남', address: '전라남도 나주시 성북동 100', hole_count: 18 },
  { id: '68', name: '서봉파크골프장', city_province: '광주', address: '광주광역시 광산구 서봉동 205-6', hole_count: 18 },
  { id: '69', name: '태안파크골프장', city_province: '충남', address: '충청남도 태안군 태안읍 기업도시로 443', hole_count: 18 },
  { id: '70', name: '수림지파크골프장', city_province: '대구', address: '대구광역시 달서구 대천동699', hole_count: 18 },
  { id: '71', name: '계룡시파크골프장', city_province: '충남', address: '충청남도 계룡시 신도안면 정장리 6', hole_count: 18 },
  { id: '72', name: '내동유수파크골프장', city_province: '경남', address: '경상남도 진주시 내동면 유수리 395-11', hole_count: 18 },
  { id: '73', name: '월라봉파크골프장', city_province: '제주', address: '제주특별자치도 서귀포시 월라봉로34번길 29(신효동)', hole_count: 18 },
  { id: '74', name: '범밤파크골프장', city_province: '부산', address: '부산광역시 강서구 범방동 1998', hole_count: 18 },
  { id: '75', name: '동구 봉무동 파크골프장', city_province: '대구', address: '대구광역시 동구 봉무동 1097-5 빗물펌프장(금호강변) 인근', hole_count: 18 },
  { id: '76', name: '담양제2파크골프장', city_province: '전남', address: '전라남도 담양군 담양읍 양각리 348-135', hole_count: 18 },
  { id: '77', name: '불로파크골프장', city_province: '대구', address: '대구광역시 동구 불로동 866-2', hole_count: 18 },
  { id: '78', name: '군포 초막골파크골프장', city_province: '경기', address: '경기도 군포시 초막골길 216번지', hole_count: 18 },
  { id: '79', name: '부주산국제파크골프장', city_province: '전남', address: '전라남도 목포시 부주로 159', hole_count: 18 },
  { id: '80', name: '울주군 범서 파크골프장', city_province: '울산', address: '울산광역시 울주군 범서읍 천상리 1041-77번지', hole_count: 18 },
  { id: '81', name: '진주종합경기장파크골프장', city_province: '경남', address: '경상남도 진주시 동진로 415 진주종합경기장내', hole_count: 18 },
  { id: '82', name: '행구수변공원파크골프장', city_province: '강원', address: '강원특별자치도 원주시 행구동 1029번지', hole_count: 18 },
  { id: '83', name: '하남시파크골프장', city_province: '경기', address: '경기도 하남시 미사대로 505', hole_count: 18 },
  { id: '84', name: '북구파크골프장', city_province: '광주', address: '광주광역시 북구 연제동 730번지(북구종합운동장내)', hole_count: 18 },
  { id: '85', name: '합천파크골프장', city_province: '경남', address: '경상남도 합천군 합천읍 합천리 20-2', hole_count: 18 },
  { id: '86', name: '갑천파크골프장(2구장)', city_province: '대전', address: '대전광역 유성구 용산동 51-2(용신교 상류)', hole_count: 18 },
  { id: '87', name: '강남파크골프장', city_province: '경북', address: '경상북도 안동시 정상동 779', hole_count: 18 },
  { id: '88', name: '횡천파크골프장 (중복)', city_province: '경남', address: '경상남도 하동군 횡천면 횡천리 639-3', hole_count: 18 },
  { id: '89', name: '인천아시아드파크골프장', city_province: '인천', address: '인천 서구 봉수대로 806 인천아시아드주경기장', hole_count: 18 },
  { id: '90', name: '황산공원 파크골프장', city_province: '경남', address: '경상남도 양산시 물금읍 증산리 999번지', hole_count: 18 },
  { id: '91', name: '가곡파크골프장', city_province: '경남', address: '경상남도 밀양시 가곡동 743-2', hole_count: 18 },
  { id: '92', name: '고창청보리파크골프장', city_province: '전북', address: '전북특별자치도 고창군 공음면 선동리 323-46', hole_count: 18 },
  { id: '93', name: '난지천파크골프장연습장', city_province: '서울', address: '서울 마포구 상암동 1538, 난지공원 내', hole_count: 18 },
  { id: '94', name: '북면 장애인 파크골프장', city_province: '경남', address: '경상남도 창원시 의창구 북면 외산리 42-2', hole_count: 18 },
  { id: '95', name: '중산파크골프장', city_province: '경기', address: '경기도 고양시 일산동구 중산로217 중산공원', hole_count: 18 },
  { id: '96', name: '횡성 전천파크골프장', city_province: '강원', address: '강원도 횡성읍 읍상리 577-1', hole_count: 18 },
  { id: '97', name: '산외파크골프장', city_province: '경남', address: '경상남도 밀양시 산외면 다죽리 1199-78', hole_count: 18 },
  { id: '98', name: '청도파크골프장', city_province: '경북', address: '경상북도 청도군 청도읍 사기점길 24', hole_count: 18 },
  { id: '99', name: '나리공원파크골프장', city_province: '경기', address: '경기도 양주시 광사동 광사로 131-66 나리공원 내', hole_count: 18 },
  { id: '100', name: '원오교파크골프장', city_province: '대구', address: '대구광역시 달성군 현풍면 원교리 889-2 원오교', hole_count: 18 },
  { id: '101', name: '삼척시 미로파크골프장', city_province: '강원', address: '강원특별자치도 삼척시 미로면 무사리 산62-10', hole_count: 18 },
  { id: '102', name: '칠십리파크골프장', city_province: '제주', address: '제주특별자치도 서귀포시 현청로 41-19 (서홍동)', hole_count: 18 },
  { id: '103', name: '구미파크골프장', city_province: '경북', address: '경상북도 고아읍 괴평리 1123', hole_count: 18 },
  { id: '104', name: '상록파크골프구장', city_province: '충남', address: '충청남도 당진시 송악읍 두곡공단로', hole_count: 18 },
  { id: '105', name: '동작파크골프장', city_province: '서울', address: '서울 동작구 동작동 327', hole_count: 18 },
  { id: '106', name: '담양제1파크골프장', city_province: '전남', address: '전라남도 담양군 담양읍 양각샛길 207', hole_count: 18 },
  { id: '107', name: '다산파크골프장', city_province: '경북', address: '경상북도 고령군 다산면 사문나루1길 30', hole_count: 18 },
  { id: '108', name: '양평파크골프장', city_province: '경기', address: '경기도 양평군 강상면 교평리419', hole_count: 18 },
  { id: '109', name: '하동군파크골프장', city_province: '경남', address: '경상남도 하동군 진교면 구 고속도로 934', hole_count: 18 },
  { id: '110', name: '점곡사촌문화골프장', city_province: '경북', address: '경상북도 의성군 점곡면 점곡길 53', hole_count: 18 },
  { id: '111', name: '광석골파크골프장', city_province: '경남', address: '경상남도 창원시 진해구 장천동 21', hole_count: 18 },
  { id: '112', name: '정발파크골프장(정발산파크골프장)', city_province: '경기', address: '경기도 고양시 일산동구 마두동 807', hole_count: 18 },
  { id: '113', name: '중랑천파크골프장(노원구) 제1파크골프장', city_province: '서울', address: '서울 노원구 월계동 230-10', hole_count: 18 },
  { id: '114', name: '금산군파크골프장', city_province: '충남', address: '충청남도 금산군 제원면 수당리 986-1', hole_count: 18 },
  { id: '115', name: '고산파크골프장', city_province: '전북', address: '전북특별자치도 완주군 고산면 읍내리 902 고산체육공원 내', hole_count: 18 },
  { id: '116', name: '울진파크골프장', city_province: '경북', address: '경상북도 울진군 근남면 수산리 369-1번지', hole_count: 18 },
  { id: '117', name: '오가낭뜰파크골프장', city_province: '세종', address: '세종특별자치시 미리내로 104', hole_count: 18 },
  { id: '118', name: '천안풍세파크골프장', city_province: '충남', address: '충청남도 천안시 동남구 풍세면 용정리 971 풍세산단 내 공원', hole_count: 18 },
  { id: '119', name: '무태파크골프장', city_province: '대구', address: '대구광역시 북구 서변동 산격대교 밑', hole_count: 18 },
  { id: '120', name: '서의성파크골프장', city_province: '경북', address: '경상북도 의성군 안계면 소보안계로 1907', hole_count: 18 },
  { id: '121', name: '중랑천파크골프장(광진구)', city_province: '서울', address: '서울 광진구 중곡동 485-7 일대', hole_count: 18 },
  { id: '122', name: '삼척시 도계파크골프장', city_province: '강원', address: '강원특별자치도 삼척시 도계읍 늑구리 105-4', hole_count: 18 },
  { id: '123', name: '남원파크골프장', city_province: '제주', address: '제주특별자치도 서귀포시 남원읍 서성로 955-82', hole_count: 18 },
  { id: '124', name: '순창군파크골프장', city_province: '전북', address: '전북특별자치도 순창군 유등면 왜이리 555-2', hole_count: 18 },
  { id: '125', name: '익산파크골프장', city_province: '전북', address: '전북특별자치도 익산시 오산면 목천리 967-1', hole_count: 18 },
  { id: '126', name: '버드내태평파크골프장', city_province: '대전', address: '대전광역시 중구 태평동515-2(가장교-태평교)', hole_count: 18 },
  { id: '127', name: '녹천파크골프장', city_province: '서울', address: '서울 도봉구 창동 796', hole_count: 18 },
  { id: '128', name: '무등산파크골프장', city_province: '광주', address: '광주광역시 동구 남문로 418-13', hole_count: 18 },
  { id: '129', name: '하대지구 파크골프장', city_province: '경남', address: '경상남도 진주시 하대동', hole_count: 18 },
  { id: '130', name: '도평파크골프장', city_province: '대구', address: '대구광역시 동구 팔공로 24길 171', hole_count: 18 },
  { id: '131', name: '김천파크골프장', city_province: '경북', address: '경상북도 김천시 지좌동157-1', hole_count: 18 },
  { id: '132', name: '계평파크골프장', city_province: '경북', address: '경상북도 안동시 계평리 717', hole_count: 18 },
  { id: '133', name: '대산파크골프장', city_province: '경남', address: '경상남도 창원시 의창구 대산면 북부리 195-3', hole_count: 18 },
  { id: '134', name: '동천 파크골프장', city_province: '울산', address: '울산광역시 중구 남외동 508-1', hole_count: 18 },
  { id: '135', name: '포천파크골프장', city_province: '경기', address: '경기도 포천시 일동면 사직리 913-4', hole_count: 18 },
  { id: '136', name: '대구강변파크골프장', city_province: '대구', address: '대구광역시 북구 서변동 1506 강변축구장 옆', hole_count: 18 },
  { id: '137', name: '거창 강변파크골프장', city_province: '경남', address: '경상남도 거창군 거창읍 대평리 강변', hole_count: 18 },
  { id: '138', name: '용인아르피아파크골프장', city_province: '경기', address: '경기도 용인시 수지구 죽전동 1003-43', hole_count: 18 },
  { id: '139', name: '우주항공파크골프장', city_province: '경남', address: '경상남도 사천시 정동면 예수리 420', hole_count: 18 },
  { id: '140', name: '마전교파크골프장', city_province: '전북', address: '전북특별자치도 전주시 완산구 서신동 738-7', hole_count: 18 },
  { id: '141', name: '한진파크골프구장', city_province: '충남', address: '충청남도 당진시 송악읍 신복운로 5', hole_count: 18 },
  { id: '142', name: '삼신교통부지 파크골프장', city_province: '경남', address: '경상남도 양산시 삼신교통부지', hole_count: 18 },
  { id: '143', name: '관악파크골프장', city_province: '서울', address: '서울 관악구 신림동 산108-10', hole_count: 18 },
  { id: '144', name: '탑정파크골프장', city_province: '충남', address: '충청남도 논산시 부적면 탑정리 475-79', hole_count: 18 },
  { id: '145', name: '둔내 둔방파크골프장', city_province: '강원', address: '강원도 횡성군 둔내면 둔방내리 563-3', hole_count: 18 },
  { id: '146', name: '성주호파크골프장', city_province: '경북', address: '경상북도 성주군 금수강산면 후평리 880-1번지', hole_count: 18 },
  { id: '147', name: '다인문암파크골프장', city_province: '경북', address: '경북 의성군 다인면 삼분리 1370-2', hole_count: 18 },
  { id: '148', name: '마전비치파크골프장', city_province: '경남', address: '경상남도 창원시 마산합포구 구산면 해양관광로 722-69', hole_count: 18 },
  { id: '149', name: '재인폭포파크골프장', city_province: '경기', address: '경기도 연천군 연천읍 고문리 127-1 일원', hole_count: 18 },
  { id: '150', name: '양지파인리조트파크골프장', city_province: '경기', address: '경기도 용인시 처인구 양지면 남평로112 양지파인리조트', hole_count: 18 },
  { id: '151', name: '잠실유수지파크골프장', city_province: '서울', address: '서울 잠실동 306(잠실 유수지)', hole_count: 18 },
  { id: '152', name: '수질복원B파크골프장', city_province: '세종', address: '세종특별자치시 대평동 646', hole_count: 18 },
  { id: '153', name: '태백파크골프장', city_province: '강원', address: '강원특별자치도 태백시 백두대간로 179 태백스포츠파크 내', hole_count: 18 },
  { id: '154', name: '왜관파크골프장', city_province: '경북', address: '경상북도 칠곡군 왜관읍 왜관리 1282', hole_count: 18 },
  { id: '155', name: '임실파크골프장', city_province: '전북', address: '전북특별자치도 임실군 오수면 충효로 2132', hole_count: 18 },
  { id: '156', name: '가조파크골프장', city_province: '경남', address: '경상남도 거창군 가조면 일부리 1121-1', hole_count: 18 },
  { id: '157', name: '문경파크골프장', city_province: '경북', address: '경상북도 문경시 흥덕동 729-1번지', hole_count: 18 },
  { id: '158', name: '진천파크골프장', city_province: '충북', address: '충청북도 진천군 진천읍 장관리', hole_count: 18 },
  { id: '159', name: '부귀파크골프장', city_province: '전북', address: '전북특별자치도 진안군 부귀면 귀상로 652-41', hole_count: 18 },
  { id: '160', name: '서재파크골프장', city_province: '대구', address: '대구광역시 달성군 다사읍 다사로 822(방천리 환경자원사업소)', hole_count: 18 },
  { id: '161', name: '웅상파크골프장', city_province: '경남', address: '경상남도 양산시 웅상읍 소주동 소남교 둔치', hole_count: 18 },
  { id: '162', name: '곰나루파크골프장', city_province: '충남', address: '충청남도 공주시 웅진동 722', hole_count: 18 },
  { id: '163', name: '교동파크골프장', city_province: '강원', address: '강원도 삼척시 교동 산26-2', hole_count: 18 },
  { id: '164', name: '광양동천파크골프장', city_province: '전남', address: '전라남도 광양시 강변동길 216', hole_count: 18 },
  { id: '165', name: '경주파크골프장(1구장)', city_province: '경북', address: '경상북도 경주시 석장동 1175-11', hole_count: 18 },
  { id: '166', name: '청석공원파크골프장', city_province: '경기', address: '경기도 광주시 경안동 청석공원 내 파크골프장', hole_count: 18 },
  { id: '167', name: '구례군파크골프장', city_province: '전남', address: '전라남도 구례군 구례읍 서시천로 106', hole_count: 18 },
  { id: '168', name: '운정파크골프장', city_province: '경기', address: '경기도 파주시 소리천로 91 (와동동)', hole_count: 18 },
  { id: '169', name: '횡성 횡성파크골프장', city_province: '강원', address: '강원특별자치도 횡성군 횡성읍 앞들동2로 45-19', hole_count: 18 },
  { id: '170', name: '포곡파크골프장', city_province: '경기', address: '경기도 용인시 처인구 포곡읍 경안천자전거길 1388', hole_count: 18 },
  { id: '171', name: '명품 파크골프장', city_province: '강원', address: '강원도 횡성군 횡성읍 정암리 514-16', hole_count: 18 },
  { id: '172', name: '온고을파크골프장', city_province: '전북', address: '전북특별자치도 전주시 덕진구 화전동 969-6 만경강하천', hole_count: 18 },
  { id: '173', name: '칠서 강나루파크골프장', city_province: '경남', address: '경상남도 함안군 칠서면 이룡리 998', hole_count: 18 },
  { id: '174', name: '화천 생활체육공원파크골프장', city_province: '강원', address: '강원특별자치도 화천군 하남면 춘화로 3225-56', hole_count: 18 },
  { id: '175', name: '이방파크골프장', city_province: '경남', address: '경상남도 창녕군 이방면 장천리 950', hole_count: 18 },
  { id: '176', name: '서남물재생센터파크골프장', city_province: '서울', address: '서울 강서구 양천로 201 (마곡91번지)', hole_count: 18 },
  { id: '177', name: '단북파크골프장', city_province: '경북', address: '경상북도 의성군 단북면 단북다인로 168', hole_count: 18 },
  { id: '178', name: '형산강파크골프장', city_province: '경북', address: '경상북도 포항시 남구 해도동 130-1번지', hole_count: 18 },
  { id: '179', name: '화천 사내파크골프장', city_province: '강원', address: '강원특별자치도 화천군 사내면 문화마을2길 16', hole_count: 18 },
  { id: '180', name: '영덕파크골프장', city_province: '경북', address: '경상북도 영덕군 천전길364-5', hole_count: 18 },
  { id: '181', name: '군위파크골프장', city_province: '대구', address: '대구광역시 군위군 군위읍 내량길 28-60', hole_count: 18 },
  { id: '182', name: '신안파크골프장', city_province: '경남', address: '경상남도 산청군 신안면 중촌갈전로 228-35', hole_count: 18 },
  { id: '183', name: '둔내 우용파크골프장', city_province: '강원', address: '강원도 횡성군 둔내면 우용리 165-1', hole_count: 18 },
  { id: '184', name: '덕산파크골프장', city_province: '경북', address: '경상북도 칠곡군 약목면 덕산리 348-7', hole_count: 18 },
  { id: '185', name: '승촌파크골프장', city_province: '광주', address: '광주광역시 남구 승촌동 588-47번지 일원(승촌공원 내)', hole_count: 18 },
  { id: '186', name: '천안백석골프장', city_province: '충남', address: '충청남도 천안시 서북구 유봉로', hole_count: 18 },
  { id: '187', name: '사암파크골프장', city_province: '부산', address: '부산광역시 강서구 신호공단', hole_count: 18 },
  { id: '188', name: '장흥파크골프장', city_province: '전남', address: '전라남도 장흥군 관산읍 옥당리 535-16', hole_count: 18 },
  { id: '189', name: '중랑구립파크골프장', city_province: '서울', address: '서울 중랑구 묵동 361-5 일대', hole_count: 18 },
  { id: '190', name: '해남파크골프장', city_province: '전남', address: '전라남도 해남군 삼산면 봉학리 154-7', hole_count: 18 },
  { id: '191', name: '하동 횡천파크골프장', city_province: '경남', address: '경상남도 하동군 횡천면 횡천리 639-3', hole_count: 18 },
  { id: '192', name: '세종중앙공원파크골프장', city_province: '세종', address: '세종특별자치시 세종동 1204', hole_count: 18 },
  { id: '193', name: '청주 오송 파크골프장', city_province: '충북', address: '충청북도 청주시 흥덕구 오송읍 생명과학단지 공원 내', hole_count: 18 },
  { id: '194', name: '오부파크골프장', city_province: '경남', address: '경상남도 산청군 오부면 오잔리', hole_count: 18 },
  { id: '195', name: '건천파크골프장', city_province: '경북', address: '경상북도 경주시 건천읍 천포리 1112번지', hole_count: 18 },
  { id: '196', name: '상주파크골프장', city_province: '경북', address: '경상북도 상주시 병성천2길44', hole_count: 18 },
  { id: '197', name: '현리근린공원파크골프장', city_province: '강원', address: '강원특별자치도 인제군 기린면 현리 785 근린공원', hole_count: 18 },
  { id: '198', name: '취병파크골프장', city_province: '강원', address: '강원특별자치도 원주시 문막읍 취병리 438-37번지', hole_count: 18 },
  { id: '199', name: '미단시티체육공원파크골프', city_province: '인천', address: '인천 중구 운북동 1279 일원', hole_count: 18 },
  { id: '200', name: '논산시파크골프장', city_province: '충남', address: '충청남도 논산시 대교동 319-39번지', hole_count: 18 },
  { id: '201', name: '무한천파크골프장', city_province: '충남', address: '충청남도 예산군 예산읍 주교리 460', hole_count: 18 },
  { id: '202', name: '회천파크골프장', city_province: '제주', address: '제주특별자치도 제주시 와흘전1길 32 제주시생활체육공원 내', hole_count: 18 },
  { id: '203', name: '보성미니파크골프장', city_province: '전남', address: '전라남도 보성군 보성읍 용문길 36-16', hole_count: 18 },
  { id: '204', name: '기장파크골프장', city_province: '부산', address: '부산광역시 기장군 정관읍 모전리677 물빛공원', hole_count: 18 },
  { id: '205', name: '알천파크골프장', city_province: '경북', address: '경상북도 경주시 구황동 290-5', hole_count: 18 },
  { id: '206', name: '우보파크골프장', city_province: '대구', address: '대구광역시 군위군 미성리', hole_count: 18 },
  { id: '207', name: '옥성파크골프장', city_province: '경북', address: '경상북도 구미시 옥성면 선상동로 1173-14', hole_count: 18 },
  { id: '208', name: '성남시파크골프장', city_province: '경기', address: '경기도 성남시 분당구 수내동 47번지', hole_count: 18 },
  { id: '209', name: '태장파크골프장', city_province: '강원', address: '강원특별자치도 원주시 태장동1346-16 둔치', hole_count: 18 },
  { id: '210', name: '송도파크골프장', city_province: '인천', address: '인천 연수구 송도동 1번지 달빛공원 내', hole_count: 18 },
  { id: '211', name: '모충파크골프장', city_province: '경남', address: '경상남도 사천시 송포동 산165-1번지', hole_count: 18 },
  { id: '212', name: '안양천생태공파크골프장', city_province: '서울', address: '서울 양천구 목동 409-379(신목동역 3번출구 부근)', hole_count: 18 },
  { id: '213', name: '가야진사 파크골프장', city_province: '경남', address: '경상남도 양산시 원동면 용당리 559번지', hole_count: 18 },
  { id: '214', name: '갑천파크골프장(1구장)', city_province: '대전', address: '대전광역시 유성구 탑립동 184-4번지 일원', hole_count: 18 },
  { id: '215', name: '산이파크골프장', city_province: '전남', address: '전라남도 해남군 산이면 초두길 10-14', hole_count: 18 },
  { id: '216', name: '덕흥동 파크골프장', city_province: '광주', address: '광주광역시 서구 덕흥동 157', hole_count: 18 },
  { id: '217', name: '호계리 파크골프장', city_province: '경남', address: '경상남도 창원시 마산회원구 내서읍 호계 본동로 59-1', hole_count: 18 },
  { id: '218', name: '단양 파크골프장', city_province: '충북', address: '충청북도 단양군 단양읍 별곡리 92', hole_count: 18 },
  { id: '219', name: '동부5개면파크골프장', city_province: '경남', address: '경상남도 진주시 사봉면 사곡리 1853', hole_count: 18 },
  { id: '220', name: '사곡파크골프장', city_province: '경북', address: '경상북도 의성군 사곡면 의성사곡로 995-9', hole_count: 18 },
  { id: '221', name: '용원동 파크골프장', city_province: '경남', address: '경상남도 창원시 용원동 1347-7', hole_count: 18 },
  { id: '222', name: '삼락다이나믹파크골프장', city_province: '부산', address: '부산광역시 사상구 삼락동 29-42', hole_count: 18 },
  { id: '223', name: '여주파크골프장', city_province: '경기', address: '경기도 여주시 강변북로 241', hole_count: 18 },
  { id: '224', name: '무안파크골프장', city_province: '전남', address: '전라남도 무안군 무안읍 성동리 1086-3', hole_count: 18 },
  { id: '225', name: '장수파크골프장', city_province: '인천', address: '인천 남동구 만수동 668', hole_count: 18 },
  { id: '226', name: '신태인파크골프장', city_province: '전북', address: '전북특별자치도 정읍시 신태인읍 신용리 881', hole_count: 18 },
  { id: '227', name: '상동파크골프장', city_province: '전남', address: '전라남도 목포시 상동 연동건널목 석현동 산거리', hole_count: 18 },
  { id: '228', name: '목행파크골프장 (충주호 파크골프장)', city_province: '충북', address: '충청북도 충주시 목행동 749-6', hole_count: 18 },
  { id: '229', name: '홍천강변파크골프장', city_province: '강원', address: '강원특별자치도 홍천군 홍천읍 갈마곡리 267-10', hole_count: 18 },
  { id: '230', name: '별내동파크골프장(남양주장애인골프장)', city_province: '경기', address: '경기도 남양주시 별내3로 244', hole_count: 18 },
  { id: '231', name: '평거지구 파크골프장', city_province: '경남', address: '경상남도 진주시 평거동 555-3', hole_count: 18 },
  { id: '232', name: '상평지구파크골프장', city_province: '경남', address: '경상남도 진주시 상평동 1067-200', hole_count: 18 },
  { id: '233', name: '홍성군파크골프장', city_province: '충남', address: '충청남도 홍성군 홍성읍 충서로1707번길 150', hole_count: 18 },
  { id: '234', name: '구리 인창파크골프장', city_province: '경기', address: '경기도 구리시 인창동 22-5', hole_count: 18 },
  { id: '235', name: '용상파크골프장', city_province: '경북', address: '경상북도 안동시 용상동 구 안동병원앞', hole_count: 18 },
  { id: '236', name: '충주 장애인 파크골프장', city_province: '충북', address: '충청북도 충주시 창현로 1400 (용관동)', hole_count: 18 },
  { id: '237', name: '군산파크골프장', city_province: '전북', address: '전북특별자치도 군산시 수송동로 58', hole_count: 18 },
  { id: '238', name: '구미 어울림파크골프장', city_province: '경북', address: '경상북도 구미시 신평동 구미시산업로193-105', hole_count: 18 },
  { id: '239', name: '지수파크골프장', city_province: '경남', address: '경상남도 진주시 지수면 용봉로150번길 23', hole_count: 18 },
  { id: '240', name: '청일파크골프장', city_province: '강원', address: '강원특별자치도 횡성군 청일면 유평리 613-1', hole_count: 18 },
  { id: '241', name: '동부권파크골프장', city_province: '경남', address: '경상남도 적중면 상부리242', hole_count: 18 },
  { id: '242', name: '강남탄천파크골프장', city_province: '서울', address: '서울특별시 강남구 세곡동 1-3', hole_count: 18 },
  { id: '243', name: '영해파크골프장', city_province: '경북', address: '경상북도 영덕군 영해면 영덕로1582 영해생활체육공원 내', hole_count: 18 },
  { id: '244', name: '상주 낙동강변 파크골프장', city_province: '경북', address: '경상북도 상주시 중동면 오상리 968-1번지', hole_count: 18 },
  { id: '245', name: '천안풍세천파크골프장', city_province: '충남', address: '충청남도 천안시 풍세면 풍서천', hole_count: 18 },
  { id: '246', name: '논공위천파크골프장', city_province: '대구', address: '대구광역시 달성군 논공읍 위천리 648', hole_count: 18 },
  { id: '247', name: '용주파크골프장', city_province: '경남', address: '경상남도 합천군 용주면 성산리 1085-1', hole_count: 18 },
  { id: '248', name: '가산공원 파크골프장', city_province: '경남', address: '경상남도 양산시 동면 가산리807', hole_count: 18 },
  { id: '249', name: '신길공원파크골프장', city_province: '경기', address: '경기도 안산시 단원구 중앙대로 114', hole_count: 18 },
  { id: '250', name: '영주파크골프장(1구장)', city_province: '경북', address: '경상북도 영주시 가흥동 1382 영주교 밑', hole_count: 18 },
  { id: '251', name: '생비량파크골프장', city_province: '경남', address: '경상남도 산청군 생비량면 가계리 939-2 생활체육공원내', hole_count: 18 },
  { id: '252', name: '구지1호근린공원 파크골프장', city_province: '대구', address: '대구광역시 달성군 구지면 내리 840 산업단지1호근린공원', hole_count: 18 },
  { id: '253', name: '율곡파크골프장', city_province: '경남', address: '경상남도 합천군 율곡면 영전리786-1', hole_count: 18 },
  { id: '254', name: '금강파크골프장', city_province: '세종', address: '세종특별자치시 세종동 747-212번지', hole_count: 18 },
  { id: '255', name: '삼락생태공원파크골프장', city_province: '부산', address: '부산광역시 사상구 삼락동 29-18번지', hole_count: 18 },
  { id: '256', name: '함양파크골프장', city_province: '경남', address: '경상남도 함양군 함양읍 하림강변길 131 하림공원 내', hole_count: 18 },
  { id: '257', name: '의성군파크골프장', city_province: '경북', address: '경상북도 의성군 비안면 동부리 162-1', hole_count: 18 },
  { id: '258', name: '이천파크골프장', city_province: '경기', address: '경기 이천시 안흥동 24', hole_count: 18 },
  { id: '259', name: '제주생활체육공원 파크골프장', city_province: '제주', address: '제주특별자치도 제주시 회천동 3-21', hole_count: 18 },
  { id: '260', name: '도고파크골프장', city_province: '충남', address: '충청남도 아산시 도고면 신언리 826', hole_count: 18 },
  { id: '261', name: '증평 파크골프장', city_province: '충북', address: '충청북도 증평군 증평읍 환경개선사업소 내', hole_count: 18 },
  { id: '262', name: '매전파크골프장', city_province: '경북', address: '경상북도 청도군 매전면 온장길 123 장연생태공원', hole_count: 18 },
  { id: '263', name: '실내체육관파크골프장', city_province: '전남', address: '전라남도 목포시 상동 349-1', hole_count: 18 },
  { id: '264', name: '영천조교파크골프장', city_province: '경북', address: '경상북도 영천시 조교동 51-1', hole_count: 18 },
  { id: '265', name: '영암파크골프장', city_province: '전남', address: '전라남도 영암군 영암읍 마당바우로 41', hole_count: 18 },
  { id: '266', name: '하양파크골프장', city_province: '경북', address: '경상북도 경산시 하양읍 동서리172-4', hole_count: 18 },
  { id: '267', name: '오수파크골프장', city_province: '경북', address: '경상북도 영천시 오수5길 75', hole_count: 18 },
  { id: '268', name: '차황파크골프장', city_province: '경남', address: '경상남도 산청군 차황면 친환경로 3581', hole_count: 18 },
  { id: '269', name: '세천 파크골프장', city_province: '대구', address: '대구광역시 달성군 다사읍 매곡리 354-1 금호강변 세천교 밑', hole_count: 18 },
  { id: '270', name: '연천파크골프장', city_province: '경기', address: '경기도 연천군 군남면 진상리 610번지', hole_count: 18 },
  { id: '271', name: '시흥시청파크골프장', city_province: '경기', address: '경기도 시흥시 장현동 702-1', hole_count: 18 },
  { id: '272', name: '동락파크골프장', city_province: '경북', address: '경상북도 구미시 진평동 880', hole_count: 18 },
  { id: '273', name: '함평 파크골프장', city_province: '전남', address: '전라남도 함평군 함평읍 곤재로 83', hole_count: 18 },
  { id: '274', name: '불갑파크골프장', city_province: '전남', address: '전라남도 영광군 불갑면 방마리', hole_count: 18 },
  { id: '275', name: '을미기파크골프장', city_province: '대전', address: '대전광역시 대덕구 대덕대로1448번길 120 을미기공원 내', hole_count: 18 },
  { id: '276', name: '풍기파크골프장', city_province: '경북', address: '경상북도 영주시 풍기읍 창락리 303-1 남원천변', hole_count: 18 },
  { id: '277', name: '춘천 소양강파크골프장', city_province: '강원', address: '강원특별자치도 춘천시 장학리 459-11', hole_count: 18 },
  { id: '278', name: '상관파크골프장', city_province: '전북', address: '전북특별자치도 완주군 상관면 신리 916', hole_count: 18 },
  { id: '279', name: '대저생태공원파크골프장', city_province: '부산', address: '부산광역시 강서구 대저1동 1-5 대저생태공원', hole_count: 18 },
  { id: '280', name: '오곡파크골프장', city_province: '전남', address: '전라남도 곡성군 오곡천변내', hole_count: 18 },
  { id: '281', name: '아천파크골프장', city_province: '경기', address: '경기도 구리시 아천동 172', hole_count: 18 },
  { id: '282', name: '단성(묵곡) 파크골프장', city_province: '경남', address: '경상남도 산청군 단성면 성철로 93번길(겁외사 옆)', hole_count: 18 },
  { id: '283', name: '남대천파크골프장', city_province: '경북', address: '경상북도 울진군 평해읍 평해리 538-4', hole_count: 18 },
  { id: '284', name: '송정파크골프장', city_province: '경남', address: '경상남도 산청군 생초면 어서리', hole_count: 18 },
  { id: '285', name: '서산파크골프장', city_province: '충남', address: '충청남도 서산시 양대동 753-4', hole_count: 18 },
  { id: '286', name: '청주 장애인 파크골프장', city_province: '충북', address: '충청북도 청주시 흥덕구 미호로 99', hole_count: 18 },
  { id: '287', name: '안양천파크골프장(9홀)', city_province: '서울', address: '서울 구로구 신도림동 271-64', hole_count: 18 },
  { id: '288', name: '쇠평파크골프장', city_province: '울산', address: '울산광역시 동구 남목3동 산153', hole_count: 18 },
  { id: '289', name: '대구과학관공원 파크골프장', city_province: '대구', address: '대구광역시 달성군 유가읍 상리 916-1', hole_count: 18 },
  { id: '290', name: '각북파크골프장', city_province: '경남', address: '경상북도 청도군 각북면 낙산1길 산들팬션앞', hole_count: 18 },
  { id: '291', name: '삼학도파크골프장', city_province: '전남', address: '전라남도 목포시 산정동 삼하도', hole_count: 18 },
  { id: '292', name: '북항파크골프장', city_province: '전남', address: '전라남도 목포시 북항 하수종말처리장', hole_count: 18 },
  { id: '293', name: '진장 파크골프장', city_province: '울산', address: '울산광역시 북구 진장동 400', hole_count: 18 },
  { id: '294', name: '군북파크골프장', city_province: '경남', address: '경상남도 함안군 군북면 사도리 1306번지', hole_count: 18 },
  { id: '295', name: '밀양파크골프장', city_province: '경남', address: '경상남도 밀양시 삼문동 631번지', hole_count: 18 },
  { id: '296', name: '양평장애인파크골프장', city_province: '경기', address: '경기도 양평군 강상면 교평리 436-2', hole_count: 18 },
  { id: '297', name: '여의도한강공원파크골프장', city_province: '서울', address: '서울 영등포구 여의도동 70-1 63빌딩 앞 둔치', hole_count: 18 },
  { id: '298', name: '칠암파크골프장', city_province: '경남', address: '경상남도 진주시 주약동 776-1', hole_count: 18 },
  { id: '299', name: '부강파크골프장', city_province: '세종', address: '세종특별자치시 부강면 금호리 823-3', hole_count: 18 },
  { id: '300', name: '하남파크골프장', city_province: '경남', address: '경상남도 밀양시 하남읍 명품십리길 34', hole_count: 18 },
  { id: '301', name: '양촌파크골프장', city_province: '경기', address: '경기도 김포시 양촌읍 황금로127번길 215-1', hole_count: 18 },
  { id: '302', name: '진천파크골프장', city_province: '대구', address: '대구광역시 달성군 화원읍 구라리 1400', hole_count: 18 },
  { id: '303', name: '학성파크골프장', city_province: '강원', address: '강원특별자치도 원주시 학성동 36번지', hole_count: 18 },
  { id: '304', name: '대곡파크골프장', city_province: '경남', address: '경상남도 진주시 대곡면 광석리 330', hole_count: 18 },
  { id: '305', name: '거제파크골프장', city_province: '경남', address: '경상남도 거제시 거제남서로 3485-17 거제스포츠파크 내', hole_count: 18 },
  { id: '306', name: '월향파크골프장', city_province: '경북', address: '경상북도 성주군 월항면 보암리 890-1', hole_count: 18 },
  { id: '307', name: '영산포체육공원파크골프장', city_province: '전남', address: '전라남도 나주시 삼영동 131-1', hole_count: 18 },
  { id: '308', name: '고전파크골프장', city_province: '경남', address: '경상남도 하동군 고전면 전도리 882-3', hole_count: 18 },
  { id: '309', name: '옥포파크골프장', city_province: '대구', address: '대구광역시 달성군 옥포읍 간경리 966-1', hole_count: 18 },
  { id: '310', name: '남해스포츠 파크골프장', city_province: '경남', address: '경상남도 남해군 서면 스포츠파크길 15 남해스포츠파크 내', hole_count: 18 },
  { id: '311', name: '음성 맹동파크골프장', city_province: '충북', address: '충청북도 음성군 맹동면 동성리 6', hole_count: 18 },
  { id: '312', name: '옥동파크골프장', city_province: '경북', address: '경상북도 안동시 옥동 1381-15', hole_count: 18 },
  { id: '313', name: '화정파크골프장', city_province: '경기', address: '경기도 고양시 덕양구 은빛로77번길 14', hole_count: 18 },
  { id: '314', name: '남해파크골프장', city_province: '전남', address: '전라남도 목포시 연산동 864', hole_count: 18 },
  { id: '315', name: '망원유수지파크골프장', city_province: '서울', address: '서울 마포구 망원동 450-3', hole_count: 18 },
  { id: '316', name: '한빛원자력파크골프장', city_province: '전남', address: '전라남도 영광군 홍농읍 성산리 494', hole_count: 18 },
  { id: '317', name: '조만강파크골프장', city_province: '경남', address: '경상남도 김해시 신문동 31-8', hole_count: 18 },
  { id: '318', name: '포천파크골프장', city_province: '경기', address: '경기 포천시 일동면 사직리 913-4', hole_count: 18 },
  { id: '319', name: '영양군 파크골프장', city_province: '경북', address: '경상북도 영양군 영양읍 삼지리 200 삼지수변공원 내', hole_count: 18 },
  { id: '320', name: '가평파크골프장', city_province: '경기', address: '경기도 가평군 청평면 대성리 388-13', hole_count: 18 },
  { id: '321', name: '렛츠런파크골프장', city_province: '제주', address: '제주특별자치도 제주시 애월읍 유수암리 1206', hole_count: 18 },
  { id: '322', name: '동두천송내파크골프장', city_province: '경기', address: '경기도 동두천시 송내동 696', hole_count: 18 },
  { id: '323', name: '성주참외 파크골프장', city_province: '경북', address: '경상북도 성주군 선남면 소학리 4-1번지 일원', hole_count: 18 },
  { id: '324', name: '진안파크골프장', city_province: '전북', address: '전북특별자치도 진안군 진안읍 운산리 76', hole_count: 18 },
  { id: '325', name: '청양 왕진나루 파크골프장', city_province: '충남', address: '충청남도 청양군 청남면 왕진리 367번지', hole_count: 18 },
  { id: '326', name: '송백리어르신체육시설 파크골프장', city_province: '경남', address: '경상남도 진주시 금산면 송백리 660-1', hole_count: 18 },
  { id: '327', name: '줄포파크골프장', city_province: '전북', address: '전북특별자치도 부안군 줄포면 생태공원로 170 부안자연생태공원 내', hole_count: 18 },
  { id: '328', name: '금천한내파크골프장', city_province: '서울', address: '서울 금천구 가산동557-3', hole_count: 18 },
  { id: '329', name: '전원파크골프장', city_province: '충남', address: '충청남도 서산시 대산읍 운산리', hole_count: 18 },
  { id: '330', name: '양평누리체육공원파크골프장', city_province: '서울', address: '서울 영등포구 양화동 10-2', hole_count: 18 },
  { id: '331', name: '영주파크골프장(2구장)', city_province: '경북', address: '경상북도 영주시 가흥동 46 가흥제1교 밑', hole_count: 18 },
  { id: '332', name: '한반도섬 파크골프장', city_province: '강원', address: '강원특별자치도 양구군 양구읍 동수리 334-17', hole_count: 18 },
  { id: '333', name: '곡성동악파크골프장', city_province: '전남', address: '전라남도 곡성군 곡성읍 교촌리 47', hole_count: 18 },
  { id: '334', name: '이순신파크골프장', city_province: '충남', address: '충청남도 아산시 염치읍 석정리 536-1', hole_count: 18 },
  { id: '335', name: '생강골파크골프장', city_province: '전북', address: '전북특별자치도 완주군 봉동읍 낙평리 795', hole_count: 18 },
  { id: '336', name: '장성군 B파크골프장', city_province: '전남', address: '전라남도 장성군 황룡면 신호리 53-1', hole_count: 18 },
  { id: '337', name: '상사파크골프장', city_province: '전남', address: '전라남도 순천시 상사면 응령리 678-7', hole_count: 18 },
  { id: '338', name: '울주군 청량 파크골프장', city_province: '울산', address: '울산광역시 울주군 청량읍 덕하리 979-63', hole_count: 18 },
  { id: '339', name: '복내파크골프장', city_province: '전남', address: '전라남도 보성군 복내리 536-16', hole_count: 18 },
  { id: '340', name: '잠실파크골프장', city_province: '서울', address: '서울 송파구 올림픽로25', hole_count: 18 },
  { id: '341', name: '천안한들파크골프장', city_province: '충남', address: '충청남도 천안시 서북구 음봉로 861-50', hole_count: 18 },
  { id: '342', name: '충주 단월 파크골프장', city_province: '충북', address: '충청북도 충주시 단월동 635-4', hole_count: 18 },
  { id: '343', name: '강변파크골프장', city_province: '부산', address: '부산광역시 사하구 을숙도대로 466', hole_count: 18 },
  { id: '344', name: '강경파크골프장', city_province: '충남', address: '충청남도 논산시 강경읍 금백로 45', hole_count: 18 },
  { id: '345', name: '북삼파크골프장', city_province: '경북', address: '경상북도 칠곡군 북삼읍 어로리 743=1', hole_count: 18 },
  { id: '346', name: '거창파크골프장(제2구장)', city_province: '경남', address: '경상남도 거창군 거창읍 심소정길 39-36', hole_count: 18 },
  { id: '347', name: '비산파크골프장A-E', city_province: '대구', address: '대구광역시 서구 비산동 2920', hole_count: 18 },
  { id: '348', name: '수원시파크골프장', city_province: '경기', address: '경기도 수원시 권선구 서수원로577번길 171(서수원칠보체육관)', hole_count: 18 },
  { id: '349', name: '안양천파크골프장(18홀)', city_province: '서울', address: '서울 구로구 고척동 60-1', hole_count: 18 },
  { id: '350', name: '공촌유수지파크골프장 (청라파크골프장)', city_province: '인천', address: '인천 서구 첨단서로 130 공촌유수지체육시설', hole_count: 18 },
  { id: '351', name: '남양주파크골프장', city_province: '경기', address: '경기도 남양주시 다산동739 다산근린공원 앞 왕숙천', hole_count: 18 },
  { id: '352', name: '북평파크골프장', city_province: '강원', address: '강원도 정선군 북평면 북평리 149-1', hole_count: 18 },
  { id: '353', name: '가포체육공원 파크골프장', city_province: '경남', address: '경상남도 창원시 마산합포구 가포신항남로 37', hole_count: 18 },
  { id: '354', name: '경주파크골프장(2구장)', city_province: '경북', address: '경상북도 경주시 충효동 7-1', hole_count: 18 },
  { id: '355', name: '금서파크골프장', city_province: '경남', address: '경상남도 산청군 금서면 동의보감로 645', hole_count: 18 },
  { id: '356', name: '오륜파크골프장', city_province: '부산', address: '부산광역시 금정구 오륜동 657-2', hole_count: 18 },
  { id: '357', name: '장천파크골프장', city_province: '경남', address: '경상남도 창원시 진해구 진해대로1099번길 149 생태숲가는길중간지점', hole_count: 18 },
  { id: '358', name: '소보파크골프장', city_province: '대구', address: '대구광역시 군위군 봉황리', hole_count: 18 },
  { id: '359', name: '남원그린파크골프장', city_province: '전북', address: '전북특별자치도 남원시 주생면 중동리 1009-43번지 일원', hole_count: 18 },
  { id: '360', name: '서산나이스파크골프장', city_province: '충남', address: '충청남도 서산시 음암면 바위백이길 12', hole_count: 18 },
  { id: '361', name: '지곡파크골프장', city_province: '경북', address: '경상북도 포항시 남구 효곡동', hole_count: 18 },
  { id: '362', name: '진천천 파크골프장', city_province: '대구', address: '대구광역시 화원읍 구라리 1400번지 일원 (구라교 하부)', hole_count: 18 },
  { id: '363', name: '군위 효령파크골프장', city_province: '대구', address: '대구광역시 군위군 효령면 장기리 116', hole_count: 18 },
  { id: '364', name: '석적파크골프장', city_province: '경북', address: '경상북도 칠곡군 석적읍 남율리 403', hole_count: 18 },
  { id: '365', name: '제천 청풍호파크골프장', city_province: '충북', address: '충청북도 제천시 금성면 중전리 176번지', hole_count: 18 },
  { id: '366', name: '서해파크골프장', city_province: '전남', address: '전라남도 목포시 연산동', hole_count: 18 },
  { id: '367', name: '고금파크골프장', city_province: '전남', address: '전라남도 완도군  고금면 농상리 768', hole_count: 18 },
  { id: '368', name: '봉산파크골프장', city_province: '경남', address: '경상남도 합천군 봉산면 서부로4344-11', hole_count: 18 },
  { id: '369', name: '운림삼별초파크골프장', city_province: '전남', address: '전라남도 진도군 의신면 사천길 15-21', hole_count: 18 },
  { id: '370', name: '춘천 서면파크골프장', city_province: '강원', address: '강원도 춘천시 서면 현암리 박사로 800', hole_count: 18 },
  { id: '371', name: '산청(모고)파크골프장', city_province: '경남', address: '경상남도 산청군 산청읍 모고리', hole_count: 18 },
  { id: '372', name: '오송KTX파크골프장', city_province: '충북', address: '충청북도 청주시 흥덕구 오송읍 오송리 358-3', hole_count: 18 },
  { id: '373', name: '시종마한파크골프장', city_province: '전남', address: '전라남도 영암군 시종면 남해당로 65', hole_count: 18 },
  { id: '374', name: '거창파크골프장(제1구장)', city_province: '경남', address: '경상남도 거창군 거창읍 심소정길 39-36', hole_count: 18 },
  { id: '375', name: '금성파크골프장', city_province: '경북', address: '경상북도 의성군 금성면 탑운길 99', hole_count: 18 },
  { id: '376', name: '첨단체육공원 파크골프장', city_province: '광주', address: '광주광역시 광산구 쌍암동 695-3 첨단생활체육공원 내', hole_count: 18 },
  { id: '377', name: '선산파크골프장', city_province: '경북', address: '경상북도 구미시 선산읍 원리1057-26', hole_count: 18 },
  { id: '378', name: '가창파크골프장', city_province: '대구', address: '대구광역시 달성군 가창면 옥분리 778-7번지', hole_count: 18 },
  { id: '379', name: '위천수변테마파크파크골프장', city_province: '대구', address: '대구 군위군 효령면 병수리 673', hole_count: 18 },
  { id: '380', name: '비봉파크골프장', city_province: '전북', address: '전북특별자치도 완주군 비봉면 소농리454 비봉면체육공원 내', hole_count: 18 },
  { id: '381', name: '화천 산천어파크골프장(2구장)', city_province: '강원', address: '강원특별자치도 화천군 하남면 춘화로 3061-17', hole_count: 18 },
  { id: '382', name: '병곡파크골프장', city_province: '경북', address: '경상북도 영덕군 병곡면 송천리 434-1', hole_count: 18 },
  { id: '383', name: '살곶이파크골프장', city_province: '서울', address: '서울 성동구 사근동 104', hole_count: 18 },
  { id: '384', name: '의흥파크골프장', city_province: '대구', address: '대구광역시 군위군 의흥면 수서리', hole_count: 18 },
  { id: '385', name: '쌍백파크골프장', city_province: '경남', address: '경상남도 합천군 쌍백면 중앙로63', hole_count: 18 },
  { id: '386', name: '당진해나루파크골프장', city_province: '충남', address: '충청남도 당진시 석문면 통정리 1349', hole_count: 18 },
  { id: '387', name: '음성 금왕파크골프장', city_province: '충북', address: '충청북도 음성군 금왕읍 오산리 산 2-4', hole_count: 18 },
  { id: '388', name: '형산장애인전용파크골프장', city_province: '경북', address: '경상북도 포항시 남구 형산강북로 371', hole_count: 18 },
  { id: '389', name: '화순파크골프장', city_province: '전남', address: '전라남도 화순군 청풍면 풍암리 93-9번지 일원', hole_count: 18 },
  { id: '390', name: '구지평촌파크골프장', city_province: '대구', address: '대구광역시 달성군 구지면 평촌리 1-10', hole_count: 18 },
  { id: '391', name: '논산시(신규)파크골프장', city_province: '충남', address: '충청남도 논산시 성동면 원봉리 718-7', hole_count: 18 },
  { id: '392', name: '청하파크골프장', city_province: '전북', address: '전북특별자치도 김제시 청하면 강변로151 근처', hole_count: 18 },
  { id: '393', name: '북부권파크골프장', city_province: '경남', address: '경상남도 합천군 야로면 월광리388-1', hole_count: 18 },
  { id: '394', name: '중랑물재생센터파크골프장', city_province: '서울', address: '서울 성동구 자동차시장3길 64', hole_count: 18 },
  { id: '395', name: '수안보온천 파크골프장', city_province: '충북', address: '충청북도 충주시 수안보면 안보리 427-4번지', hole_count: 18 },
  { id: '396', name: '대상파크골프장', city_province: '광주', address: '광주광역시 북구 월출동 968', hole_count: 18 },
  { id: '397', name: '천안도솔파크골프장', city_province: '충남', address: '충청남도 천안시 동남구 천안대로 844 도솔광장 내', hole_count: 18 },
  { id: '398', name: '달서강창파크골프장', city_province: '대구', address: '대구광역시 달서구 파호동 401-2', hole_count: 18 },
  { id: '399', name: '청송파크골프장', city_province: '경북', address: '경상북도 청송군 청송읍 송생리 784-1', hole_count: 18 },
  { id: '400', name: '고로파크골프장', city_province: '대구', address: '대구광역시 군위군 삼국유사면 석산리 560', hole_count: 18 },
  { id: '401', name: '삽교파크골프구장', city_province: '충남', address: '충청남도 당진시 신평면 삽교호 호수공원내', hole_count: 18 },
  { id: '402', name: '둔포파크골프장', city_province: '충남', address: '충청남도 아산시 둔포면 석곡리 1480', hole_count: 18 },
  { id: '403', name: '곡교천파크골프장', city_province: '충남', address: '충청남도 아산시 권곡동 331-1', hole_count: 18 },
  { id: '404', name: '보령파크골프구장', city_province: '충남', address: '충청남도 보령시 웅천읍 오천리 534-1', hole_count: 18 },
  { id: '405', name: '마전비치파크골프장', city_province: '경남', address: '경상남도 창원시 마산합포구 구산면 해양관광로 722-69', hole_count: 18 },
  { id: '406', name: '풍호공원 파크골프장', city_province: '경남', address: '경상남도 창원시 진해구 풍호동 26-1', hole_count: 18 },
  { id: '407', name: '남원파크골프장', city_province: '전북', address: '전라북도 남원시 월락동 248', hole_count: 18 },
  { id: '408', name: '익산 어울림파크골프장', city_province: '전북', address: '전북 익산시 오산면 목천리 967-1', hole_count: 18 },
  { id: '409', name: '괴산파크골프장', city_province: '충북', address: '충청북도 괴산군 괴산읍 정용리 694-25', hole_count: 18 },
  { id: '410', name: '선남면파크골프장', city_province: '경북', address: '경상북도 성주군 선남면 관화리 714 체육공원 내', hole_count: 18 },
  { id: '411', name: '청심빌리지파크골프장', city_province: '경기', address: '경기도 가평군 설악면 송산리711 청심빌리지', hole_count: 18 },
  { id: '412', name: '도천파크골프장', city_province: '경남', address: '경상남도 창녕군 도천면 도천리 770', hole_count: 18 },
  { id: '413', name: '양양남대천파크골프장', city_province: '강원', address: '강원도 양양군 양양읍 송암리 540번지', hole_count: 18 },
  { id: '414', name: '한솔파크골프장', city_province: '세종', address: '세종특별자치시 가람동 762-3', hole_count: 18 },
  { id: '415', name: '청주 호미골 파크골프장', city_province: '충북', address: '충청북도 청주시 상당구 용정동 25', hole_count: 18 },
  { id: '416', name: '무주파크골프장', city_province: '전북', address: '전북특별자치도 무주군 설천면 소천리 883-1', hole_count: 18 },
  { id: '417', name: '조천파크골프장', city_province: '세종', address: '세종특별자치시 조치원읍 평리 120', hole_count: 18 },
  { id: '418', name: '수성팔현파크골프장', city_province: '대구', address: '대구광역시 수성구 고모동 20-3 수성패미리파크', hole_count: 18 },
  { id: '419', name: '성서5차산업단지파크골프장', city_province: '대구', address: '대구광역시 달성군 다사읍 세천리 1691', hole_count: 18 },
  { id: '420', name: '이서파크골프장', city_province: '전북', address: '전북특별자치도 완주군 이서면 용서리 777-2 지사울공원', hole_count: 18 },
  { id: '421', name: '가야곡파크골프장', city_province: '충남', address: '충청남도 논산시 가야곡면 덕은로 365', hole_count: 18 },
  { id: '422', name: '중랑천파크골프장(동대문구)', city_province: '서울', address: '서울 동대문구 장안동 204-21', hole_count: 18 },
  { id: '423', name: '대소원 파크골프장', city_province: '충북', address: '충청북도 충주시 대소원면 새터2길 29-15', hole_count: 18 },
  { id: '424', name: '금천파크골프장', city_province: '경북', address: '경상북도 청도군 금천면 동곡리 새들보옆', hole_count: 18 },
  { id: '425', name: '강창학파크골프장', city_province: '제주', address: '제주특별자치도 서귀포시 강정동 1353', hole_count: 18 },
  { id: '426', name: '달성보파크골프장', city_province: '대구', address: '대구광역시 달성군 논공읍 남리 6-5 (달성보 하류)', hole_count: 18 },
  { id: '427', name: '둔산파크골프장', city_province: '전북', address: '전북특별자치도 완주군 봉동읍 둔산리 881', hole_count: 18 },
  { id: '428', name: '남구파크골프장', city_province: '대구', address: '대구광역시 남구 봉덕동 산128-1', hole_count: 18 },
  { id: '429', name: '강창교 파크골프장', city_province: '대구', address: '대구광역시 달성군 다사읍 매곡리 91 (금호강 체육시설 강창교 밑)', hole_count: 18 },
  { id: '430', name: '월드컵(노을)공원파크골프장', city_province: '서울', address: '서울 마포구 상암동 481-6 (노을공원 내)', hole_count: 18 },
  { id: '431', name: '음성 생극 파크골프장', city_province: '충북', address: '충청북도 음성군 생극면 신양리 793-2', hole_count: 18 },
  { id: '432', name: '예천 한천파크골프장', city_province: '경북', address: '경상북도 예천군 예천읍 왕신길 84-9', hole_count: 18 }
]

export const MOCK_RANKINGS = {}

export const MOCK_MY_SCORES = []
